-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         8.0.30 - MySQL Community Server - GPL
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para movie_recommendation
CREATE DATABASE IF NOT EXISTS `movie_recommendation` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `movie_recommendation`;

-- Volcando estructura para tabla movie_recommendation.movies
CREATE TABLE IF NOT EXISTS `movies` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `genre` varchar(255) DEFAULT NULL,
  `description` text,
  `director` varchar(255) DEFAULT NULL,
  `actors` text,
  `release_year` int DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `language` varchar(50) DEFAULT NULL,
  `poster` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=109 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Volcando datos para la tabla movie_recommendation.movies: ~108 rows (aproximadamente)
INSERT INTO `movies` (`id`, `title`, `genre`, `description`, `director`, `actors`, `release_year`, `duration`, `language`, `poster`) VALUES
	(1, 'Inception', 'Sci-Fi', 'A thief who steals secrets through dream-sharing technology.', 'Christopher Nolan', 'Leonardo DiCaprio, Joseph Gordon-Levitt', 2010, NULL, NULL, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg'),
	(2, 'The Matrix', 'Sci-Fi', 'A computer hacker learns about the true nature of reality.', 'The Wachowskis', 'Keanu Reeves, Laurence Fishburne', 1999, NULL, NULL, 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg'),
	(3, 'Interstellar', 'Sci-Fi', 'A group of explorers travel through a wormhole in space.', 'Christopher Nolan', 'Matthew McConaughey, Anne Hathaway', 2014, NULL, NULL, NULL),
	(4, 'The Prestige', 'Drama', 'Two rival magicians engage in a battle of wits.', 'Christopher Nolan', 'Hugh Jackman, Christian Bale', 2006, NULL, NULL, NULL),
	(5, 'Memento', 'Thriller', 'A man with short-term memory loss attempts to track his wife\'s killer.', 'Christopher Nolan', 'Guy Pearce, Carrie-Anne Moss', 2000, NULL, NULL, 'https://m.media-amazon.com/images/M/MV5BYmQ3MjliNjAtNWFiZS00YWI1LTlmZTktMzBiNDE1NjRhZjU0XkEyXkFqcGc@._V1_SX300.jpg'),
	(6, 'The Dark Knight', 'Action', 'When the menace known as The Joker wreaks havoc, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'Christopher Nolan', 'Christian Bale, Heath Ledger, Aaron Eckhart', 2008, 152, 'English', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg'),
	(7, 'Pulp Fiction', 'Crime', 'The lives of two hitmen, a boxer, a gangster, and his wife intertwine in a tale of violence and redemption.', 'Quentin Tarantino', 'John Travolta, Uma Thurman, Samuel L. Jackson', 1994, 154, 'English', 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_SX300.jpg'),
	(8, 'Forrest Gump', 'Drama', 'The story of a man with a low IQ who accomplishes great things in life while influencing important historical events.', 'Robert Zemeckis', 'Tom Hanks, Robin Wright, Gary Sinise', 1994, 142, 'English', 'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg'),
	(9, 'The Godfather', 'Crime', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'Francis Ford Coppola', 'Marlon Brando, Al Pacino, James Caan', 1972, 175, 'English', 'https://m.media-amazon.com/images/M/MV5BYTJkNGQyZDgtZDQ0NC00MDM0LWEzZWQtYzUzZDEwMDljZWNjXkEyXkFqcGc@._V1_SX300.jpg'),
	(10, 'The Shawshank Redemption', 'Drama', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Frank Darabont', 'Tim Robbins, Morgan Freeman, Bob Gunton', 1994, 142, 'English', 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg'),
	(11, 'The Avengers', 'Action', 'Earth’s mightiest heroes must come together to stop Loki from enslaving humanity.', 'Joss Whedon', 'Robert Downey Jr., Chris Evans, Scarlett Johansson', 2012, 143, 'English', 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg'),
	(12, 'Parasite', 'Thriller', 'A poor family schemes to become employed by a wealthy family and infiltrates their household.', 'Bong Joon Ho', 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong', 2019, 132, 'Korean', 'https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX300.jpg'),
	(13, 'Titanic', 'Romance', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious Titanic.', 'James Cameron', 'Leonardo DiCaprio, Kate Winslet, Billy Zane', 1997, 195, 'English', 'https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX300.jpg'),
	(14, 'Inglourious Basterds', 'War', 'A group of Jewish U.S. soldiers plan to assassinate Nazi leaders during World War II.', 'Quentin Tarantino', 'Brad Pitt, Diane Kruger, Eli Roth', 2009, 153, 'English', 'https://m.media-amazon.com/images/M/MV5BODZhMWJlNjYtNDExNC00MTIzLTllM2ItOGQ2NGVjNDQ3MzkzXkEyXkFqcGc@._V1_SX300.jpg'),
	(15, 'The Lion King', 'Animation', 'A lion prince, Simba, flees his kingdom after the murder of his father, only to learn the true meaning of responsibility and bravery.', 'Roger Allers, Rob Minkoff', 'Matthew Broderick, Jeremy Irons, James Earl Jones', 1994, 88, 'English', 'https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX300.jpg'),
	(16, 'The Lord of the Rings: The Fellowship of the Ring', 'Fantasy', 'A meek Hobbit and eight companions set out on a journey to destroy a powerful ring and save Middle-earth from the Dark Lord Sauron.', 'Peter Jackson', 'Elijah Wood, Ian McKellen, Orlando Bloom', 2001, 178, 'English', 'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_SX300.jpg'),
	(17, 'The Lord of the Rings: The Two Towers', 'Fantasy', 'While Frodo and Sam edge closer to Mordor with the help of Gollum, the divided fellowship makes a stand against Sauron\'s new ally, Saruman.', 'Peter Jackson', 'Elijah Wood, Ian McKellen, Viggo Mortensen', 2002, 179, 'English', 'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_SX300.jpg'),
	(18, 'The Lord of the Rings: The Return of the King', 'Fantasy', 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'Peter Jackson', 'Elijah Wood, Ian McKellen, Viggo Mortensen', 2003, 201, 'English', 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_SX300.jpg'),
	(19, 'Star Wars: Episode IV - A New Hope', 'Sci-Fi', 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire\'s world-destroying battle station.', 'George Lucas', 'Mark Hamill, Harrison Ford, Carrie Fisher', 1977, 121, 'English', 'https://m.media-amazon.com/images/M/MV5BOGUwMDk0Y2MtNjBlNi00NmRiLTk2MWYtMGMyMDlhYmI4ZDBjXkEyXkFqcGc@._V1_SX300.jpg'),
	(20, 'Star Wars: Episode V - The Empire Strikes Back', 'Sci-Fi', 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins training with Jedi Master Yoda.', 'Irvin Kershner', 'Mark Hamill, Harrison Ford, Carrie Fisher', 1980, 124, 'English', 'https://m.media-amazon.com/images/M/MV5BMTkxNGFlNDktZmJkNC00MDdhLTg0MTEtZjZiYWI3MGE5NWIwXkEyXkFqcGc@._V1_SX300.jpg'),
	(21, 'Star Wars: Episode VI - Return of the Jedi', 'Sci-Fi', 'After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star.', 'Richard Marquand', 'Mark Hamill, Harrison Ford, Carrie Fisher', 1983, 131, 'English', 'https://m.media-amazon.com/images/M/MV5BNWEwOTI0MmUtMGNmNy00ODViLTlkZDQtZTg1YmQ3MDgyNTUzXkEyXkFqcGc@._V1_SX300.jpg'),
	(22, 'Gladiator', 'Action', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'Ridley Scott', 'Russell Crowe, Joaquin Phoenix, Connie Nielsen', 2000, 155, 'English', 'https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_SX300.jpg'),
	(23, 'The Silence of the Lambs', 'Thriller', 'A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer.', 'Jonathan Demme', 'Jodie Foster, Anthony Hopkins, Scott Glenn', 1991, 118, 'English', 'https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_SX300.jpg'),
	(24, 'Schindler\'s List', 'Biography', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.', 'Steven Spielberg', 'Liam Neeson, Ralph Fiennes, Ben Kingsley', 1993, 195, 'English', 'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_SX300.jpg'),
	(25, 'Fight Club', 'Drama', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 'David Fincher', 'Brad Pitt, Edward Norton, Helena Bonham Carter', 1999, 139, 'English', 'https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_SX300.jpg'),
	(26, 'Avatar', 'Sci-Fi', 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', 'James Cameron', 'Sam Worthington, Zoe Saldana, Sigourney Weaver', 2009, 162, 'English', 'https://m.media-amazon.com/images/M/MV5BMDEzMmQwZjctZWU2My00MWNlLWE0NjItMDJlYTRlNGJiZjcyXkEyXkFqcGc@._V1_SX300.jpg'),
	(27, 'Coco', 'Animation', 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather.', 'Lee Unkrich, Adrian Molina', 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt', 2017, 105, 'Spanish', 'https://m.media-amazon.com/images/M/MV5BMDIyM2E2NTAtMzlhNy00ZGUxLWI1NjgtZDY5MzhiMDc5NGU3XkEyXkFqcGc@._V1_SX300.jpg'),
	(28, 'Joker', 'Drama', 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. This pushes him into a downward spiral.', 'Todd Phillips', 'Joaquin Phoenix, Robert De Niro, Zazie Beetz', 2019, 122, 'English', 'https://m.media-amazon.com/images/M/MV5BNzY3OWQ5NDktNWQ2OC00ZjdlLThkMmItMDhhNDk3NTFiZGU4XkEyXkFqcGc@._V1_SX300.jpg'),
	(29, 'Black Panther', 'Action', 'T\'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future.', 'Ryan Coogler', 'Chadwick Boseman, Michael B. Jordan, Lupita Nyong\'o', 2018, 134, 'English', 'https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg'),
	(30, 'Toy Story', 'Animation', 'A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy\'s bedroom.', 'John Lasseter', 'Tom Hanks, Tim Allen, Don Rickles', 1995, 81, 'English', 'https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg'),
	(31, 'Goodfellas', 'Crime', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.', 'Martin Scorsese', 'Robert De Niro, Ray Liotta, Joe Pesci', 1990, 145, 'English', 'https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_SX300.jpg'),
	(32, 'Se7en', 'Thriller', 'Two detectives hunt a serial killer who uses the seven deadly sins as his modus operandi.', 'David Fincher', 'Brad Pitt, Morgan Freeman, Gwyneth Paltrow', 1995, 127, 'English', 'https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_SX300.jpg'),
	(33, 'The Social Network', 'Biography', 'The story of the founders of the social-networking website Facebook.', 'David Fincher', 'Jesse Eisenberg, Andrew Garfield, Justin Timberlake', 2010, 120, 'English', 'https://m.media-amazon.com/images/M/MV5BMjlkNTE5ZTUtNGEwNy00MGVhLThmZjMtZjU1NDE5Zjk1NDZkXkEyXkFqcGc@._V1_SX300.jpg'),
	(34, 'Django Unchained', 'Western', 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.', 'Quentin Tarantino', 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio', 2012, 165, 'English', 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg'),
	(35, 'The Wolf of Wall Street', 'Biography', 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker living the high life to his fall involving crime and corruption.', 'Martin Scorsese', 'Leonardo DiCaprio, Jonah Hill, Margot Robbie', 2013, 180, 'English', 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg'),
	(36, 'Up', 'Animation', '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.', 'Pete Docter, Bob Peterson', 'Edward Asner, Jordan Nagai, Christopher Plummer', 2009, 96, 'English', 'https://m.media-amazon.com/images/M/MV5BNmI1ZTc5MWMtMDYyOS00ZDc2LTkzOTAtNjQ4NWIxNjYyNDgzXkEyXkFqcGc@._V1_SX300.jpg'),
	(37, 'Spirited Away', 'Animation', 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.', 'Hayao Miyazaki', 'Rumi Hiiragi, Miyu Irino, Mari Natsuki', 2001, 125, 'Japanese', 'https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_SX300.jpg'),
	(38, 'Your Name', 'Animation', 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies.', 'Makoto Shinkai', 'Ryunosuke Kamiki, Mone Kamishiraishi, Ryo Narita', 2016, 106, 'Japanese', 'https://m.media-amazon.com/images/M/MV5BYzY1OWZiN2YtMWU3My00M2YyLWI1M2EtNTljMTMwMzM5NDQ0XkEyXkFqcGc@._V1_SX300.jpg'),
	(39, 'The Grand Budapest Hotel', 'Comedy', 'A writer encounters the owner of an aging high-class hotel and hears his tale of how he took over and defended it.', 'Wes Anderson', 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric', 2014, 99, 'English', 'https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg'),
	(40, 'Shutter Island', 'Thriller', 'In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.', 'Martin Scorsese', 'Leonardo DiCaprio, Emily Mortimer, Mark Ruffalo', 2010, 138, 'English', 'https://m.media-amazon.com/images/M/MV5BN2FjNWExYzEtY2YzOC00YjNlLTllMTQtNmIwM2Q1YzBhOWM1XkEyXkFqcGc@._V1_SX300.jpg'),
	(41, 'La La Land', 'Romance', 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.', 'Damien Chazelle', 'Ryan Gosling, Emma Stone, John Legend', 2016, 128, 'English', 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg'),
	(42, 'The Pianist', 'Biography', 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto during World War II.', 'Roman Polanski', 'Adrien Brody, Thomas Kretschmann, Frank Finlay', 2002, 150, 'English', 'https://m.media-amazon.com/images/M/MV5BMjEwNmEwYjgtNTk3ZC00NjljLTg5ZDctZTY3ZGQwZjRkZmQxXkEyXkFqcGc@._V1_SX300.jpg'),
	(43, 'The Incredibles', 'Animation', 'A family of undercover superheroes attempts to live a quiet suburban life but is forced back into action to save the world.', 'Brad Bird', 'Craig T. Nelson, Holly Hunter, Samuel L. Jackson', 2004, 115, 'English', 'https://m.media-amazon.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_SX300.jpg'),
	(44, 'Finding Nemo', 'Animation', 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.', 'Andrew Stanton, Lee Unkrich', 'Albert Brooks, Ellen DeGeneres, Alexander Gould', 2003, 100, 'English', 'https://m.media-amazon.com/images/M/MV5BMTc5NjExNTA5OV5BMl5BanBnXkFtZTYwMTQ0ODY2._V1_SX300.jpg'),
	(45, 'The Breakfast Club', 'Comedy', 'Five high school students meet in Saturday detention and discover how they have a lot more in common than they thought.', 'John Hughes', 'Emilio Estevez, Judd Nelson, Molly Ringwald', 1985, 97, 'English', 'https://m.media-amazon.com/images/M/MV5BZTZiMGU1MWMtNjk0Yi00ZjNjLTljMDEtMDhkNGE2OWY3YzZiXkEyXkFqcGc@._V1_SX300.jpg'),
	(46, 'Avengers: Endgame', 'Action', 'After the devastating events of Avengers: Infinity War, the Avengers assemble once more to reverse Thanos\' actions and restore balance.', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Evans, Mark Ruffalo', 2019, 181, 'English', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg'),
	(47, 'The Green Mile', 'Drama', 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.', 'Frank Darabont', 'Tom Hanks, Michael Clarke Duncan, David Morse', 1999, 189, 'English', 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg'),
	(48, 'Interstellar', 'Sci-Fi', 'A team of explorers travels through a wormhole in space in an attempt to ensure humanity\'s survival.', 'Christopher Nolan', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain', 2014, 169, 'English', NULL),
	(49, 'The Truman Show', 'Drama', 'An insurance salesman discovers his entire life is a reality TV show.', 'Peter Weir', 'Jim Carrey, Ed Harris, Laura Linney', 1998, 103, 'English', 'https://m.media-amazon.com/images/M/MV5BNzA3ZjZlNzYtMTdjMy00NjMzLTk5ZGYtMTkyYzNiOGM1YmM3XkEyXkFqcGc@._V1_SX300.jpg'),
	(50, 'Casablanca', 'Romance', 'A cynical American expatriate struggles to decide whether or not he should help his former lover and her fugitive husband escape French Morocco.', 'Michael Curtiz', 'Humphrey Bogart, Ingrid Bergman, Paul Henreid', 1942, 102, 'English', 'https://m.media-amazon.com/images/M/MV5BNWEzN2U1YTYtYTQyMS00NTVkLWE2NGQtZWFlMmM0MDNjMmRiXkEyXkFqcGc@._V1_SX300.jpg'),
	(51, 'The Terminator', 'Sci-Fi', 'A cyborg assassin is sent back in time to kill Sarah Connor, whose unborn son will lead the resistance against machines.', 'James Cameron', 'Arnold Schwarzenegger, Linda Hamilton, Michael Biehn', 1984, 107, 'English', 'https://m.media-amazon.com/images/M/MV5BZmE0YzIxM2QtMGNlMi00MjRmLWE3MWMtOWQzMGVjMmU0YTFmXkEyXkFqcGc@._V1_SX300.jpg'),
	(52, 'Saving Private Ryan', 'War', 'Following the Normandy landings, a group of U.S. soldiers goes behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 'Steven Spielberg', 'Tom Hanks, Matt Damon, Tom Sizemore', 1998, 169, 'English', 'https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_SX300.jpg'),
	(53, 'The Shining', 'Horror', 'A family heads to an isolated hotel where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings.', 'Stanley Kubrick', 'Jack Nicholson, Shelley Duvall, Danny Lloyd', 1980, 146, 'English', 'https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_SX300.jpg'),
	(54, '2001: A Space Odyssey', 'Sci-Fi', 'After discovering a mysterious artifact on the moon, mankind sets off on a journey to find its origins with the help of an intelligent supercomputer.', 'Stanley Kubrick', 'Keir Dullea, Gary Lockwood, William Sylvester', 1968, 149, 'English', 'https://m.media-amazon.com/images/M/MV5BNjU0NDFkMTQtZWY5OS00MmZhLTg3Y2QtZmJhMzMzMWYyYjc2XkEyXkFqcGc@._V1_SX300.jpg'),
	(55, 'Braveheart', 'Action', 'Scottish warrior William Wallace leads his countrymen in a rebellion against the oppressive English rule.', 'Mel Gibson', 'Mel Gibson, Sophie Marceau, Patrick McGoohan', 1995, 178, 'English', 'https://m.media-amazon.com/images/M/MV5BNGMxZDBhNGQtYTZlNi00N2UzLWI4NDEtNmUzNWM2NTdmZDA0XkEyXkFqcGc@._V1_SX300.jpg'),
	(56, 'Amélie', 'Romance', 'Amélie, an innocent and naive girl in Paris, decides to change the lives of those around her for the better.', 'Jean-Pierre Jeunet', 'Audrey Tautou, Mathieu Kassovitz, Rufus', 2001, 122, 'French', 'https://m.media-amazon.com/images/M/MV5BOTNmYzY0MWQtZGZmNy00Y2Y4LWFmMDQtMTZjYTdiYzEwZGQ2XkEyXkFqcGc@._V1_SX300.jpg'),
	(57, 'Whiplash', 'Drama', 'A promising young drummer enrolls at a cut-throat music conservatory, where his dreams of greatness are mentored by an instructor who will stop at nothing.', 'Damien Chazelle', 'Miles Teller, J.K. Simmons, Melissa Benoist', 2014, 106, 'English', 'https://m.media-amazon.com/images/M/MV5BMmNkODhkYjctMDMyOC00ZTNjLTkwZTItM2ExMTAxMGU1ZGQ1XkEyXkFqcGc@._V1_SX300.jpg'),
	(58, 'The Big Lebowski', 'Comedy', 'Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and ends up in a whirlwind of chaos.', 'Joel Coen, Ethan Coen', 'Jeff Bridges, John Goodman, Julianne Moore', 1998, 117, 'English', 'https://m.media-amazon.com/images/M/MV5BY2E3OWQ5OWYtYTRkMC00NjVjLWIzZDQtNmRmM2ZiYTIyYmYxXkEyXkFqcGc@._V1_SX300.jpg'),
	(59, 'The Good, the Bad and the Ugly', 'Western', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold.', 'Sergio Leone', 'Clint Eastwood, Eli Wallach, Lee Van Cleef', 1966, 178, 'Italian', 'https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_SX300.jpg'),
	(60, 'Inside Out', 'Animation', 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions conflict on how to navigate her new environment.', 'Pete Docter, Ronnie del Carmen', 'Amy Poehler, Bill Hader, Lewis Black', 2015, 95, 'English', 'https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg'),
	(61, 'Crouching Tiger, Hidden Dragon', 'Action', 'A young Chinese warrior steals a sword from a famed swordsman and then escapes into a world of romantic adventure.', 'Ang Lee', 'Chow Yun-Fat, Michelle Yeoh, Zhang Ziyi', 2000, 120, 'Mandarin', 'https://m.media-amazon.com/images/M/MV5BMzRmMTU2OWEtZjI0Ni00MGRhLThjOTItZTJiNmM4MDk0ZWU2XkEyXkFqcGc@._V1_SX300.jpg'),
	(62, 'Pan\'s Labyrinth', 'Fantasy', 'In the aftermath of the Spanish Civil War, young Ofelia enters a magical world where she must prove her worth.', 'Guillermo del Toro', 'Ivana Baquero, Ariadna Gil, Sergi López', 2006, 118, 'Spanish', 'https://m.media-amazon.com/images/M/MV5BOTc1NTAxMWItMWFlNy00MmU2LTkwMTMtNzMwOTg5OTQ5YTFiXkEyXkFqcGc@._V1_SX300.jpg'),
	(63, 'City of God', 'Crime', 'In the slums of Rio, two kids\' paths diverge as one struggles to become a photographer and the other a kingpin.', 'Fernando Meirelles, Kátia Lund', 'Alexandre Rodrigues, Leandro Firmino, Matheus Nachtergaele', 2002, 130, 'Portuguese', 'https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_SX300.jpg'),
	(64, 'The Pursuit of Happyness', 'Biography', 'A struggling salesman takes custody of his son as he\'s poised to begin a life-changing professional career.', 'Gabriele Muccino', 'Will Smith, Jaden Smith, Thandiwe Newton', 2006, 117, 'English', 'https://m.media-amazon.com/images/M/MV5BMTQ5NjQ0NDI3NF5BMl5BanBnXkFtZTcwNDI0MjEzMw@@._V1_SX300.jpg'),
	(65, 'Slumdog Millionaire', 'Drama', 'A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of "Who Wants to Be a Millionaire?".', 'Danny Boyle, Loveleen Tandan', 'Dev Patel, Freida Pinto, Saurabh Shukla', 2008, 120, 'Hindi', 'https://m.media-amazon.com/images/M/MV5BMTE5ZTRkYWEtZmU5MC00NDJjLTk3NmUtZGJlYTM2MmQ3NTJkXkEyXkFqcGc@._V1_SX300.jpg'),
	(66, 'The Prestige', 'Mystery', 'After a tragic accident, two stage magicians engage in a bitter rivalry to create the ultimate illusion.', 'Christopher Nolan', 'Hugh Jackman, Christian Bale, Scarlett Johansson', 2006, 130, 'English', NULL),
	(67, 'Requiem for a Dream', 'Drama', 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.', 'Darren Aronofsky', 'Ellen Burstyn, Jared Leto, Jennifer Connelly', 2000, 102, 'English', 'https://m.media-amazon.com/images/M/MV5BN2ZlMjIzZjctYzA2My00ZWYyLWI4ZjctMGI2NWYyNzFiZjAwXkEyXkFqcGc@._V1_SX300.jpg'),
	(68, 'A Beautiful Mind', 'Biography', 'After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the worse.', 'Ron Howard', 'Russell Crowe, Ed Harris, Jennifer Connelly', 2001, 135, 'English', 'https://m.media-amazon.com/images/M/MV5BNzljZTk5ZDgtZTQ1Zi00NTM4LThlOGUtZDk2MGM4NDQ4NWQyXkEyXkFqcGc@._V1_SX300.jpg'),
	(69, 'Blade Runner 2049', 'Sci-Fi', 'A young blade runner uncovers a long-buried secret that has the potential to plunge society into chaos.', 'Denis Villeneuve', 'Ryan Gosling, Harrison Ford, Ana de Armas', 2017, 164, 'English', 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg'),
	(70, 'The Hateful Eight', 'Western', 'In the dead of a Wyoming winter, bounty hunters seek shelter in a cabin, encountering betrayal and deception.', 'Quentin Tarantino', 'Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh', 2015, 187, 'English', 'https://m.media-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_SX300.jpg'),
	(71, 'Her', 'Romance', 'A lonely writer develops an unlikely relationship with an operating system designed to meet his every need.', 'Spike Jonze', 'Joaquin Phoenix, Scarlett Johansson, Amy Adams', 2013, 126, 'English', 'https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_SX300.jpg'),
	(72, 'The Revenant', 'Adventure', 'A frontiersman on a fur trading expedition fights for survival after being mauled by a bear and left for dead.', 'Alejandro González Iñárritu', 'Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson', 2015, 156, 'English', 'https://m.media-amazon.com/images/M/MV5BYTgwNmQzZDctMjNmOS00OTExLTkwM2UtNzJmOTJhODFjOTdlXkEyXkFqcGc@._V1_SX300.jpg'),
	(73, 'Mad Max: Fury Road', 'Action', 'In a post-apocalyptic wasteland, Max helps a rebellious woman and a group of female prisoners escape a tyrant.', 'George Miller', 'Tom Hardy, Charlize Theron, Nicholas Hoult', 2015, 120, 'English', 'https://m.media-amazon.com/images/M/MV5BZDRkODJhOTgtOTc1OC00NTgzLTk4NjItNDgxZDY4YjlmNDY2XkEyXkFqcGc@._V1_SX300.jpg'),
	(74, 'The Great Gatsby', 'Drama', 'A writer and wall street trader, Nick, finds himself drawn to the past and lifestyle of his millionaire neighbor.', 'Baz Luhrmann', 'Leonardo DiCaprio, Carey Mulligan, Joel Edgerton', 2013, 143, 'English', 'https://m.media-amazon.com/images/M/MV5BMTkxNTk1ODcxNl5BMl5BanBnXkFtZTcwMDI1OTMzOQ@@._V1_SX300.jpg'),
	(75, 'The Shape of Water', 'Fantasy', 'A mute cleaning lady forms a unique relationship with an amphibious creature being held in captivity.', 'Guillermo del Toro', 'Sally Hawkins, Octavia Spencer, Michael Shannon', 2017, 123, 'English', 'https://m.media-amazon.com/images/M/MV5BOGFlMTM2MTgtZDdlMy00ZDZlLWFjOTUtZDMzMGEwNmNiMWY0XkEyXkFqcGc@._V1_SX300.jpg'),
	(76, 'Moonlight', 'Drama', 'A young African-American man grapples with his identity and sexuality while experiencing the struggles of childhood, adolescence, and adulthood.', 'Barry Jenkins', 'Mahershala Ali, Naomie Harris, Trevante Rhodes', 2016, 111, 'English', 'https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg'),
	(77, 'Jojo Rabbit', 'Comedy', 'A young boy in Hitler\'s army finds out his mother is hiding a Jewish girl in their home.', 'Taika Waititi', 'Roman Griffin Davis, Thomasin McKenzie, Taika Waititi', 2019, 108, 'English', 'https://m.media-amazon.com/images/M/MV5BYmFmNmUyMjYtZTFjNS00OWQyLThhZmMtMGZkYTQ3YjY0ZDQ1XkEyXkFqcGc@._V1_SX300.jpg'),
	(78, 'The Irishman', 'Crime', 'A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.', 'Martin Scorsese', 'Robert De Niro, Al Pacino, Joe Pesci', 2019, 209, 'English', 'https://m.media-amazon.com/images/M/MV5BMTY2YThkNmQtOWJhYy00ZDc3LWEzOGEtMmQwNzM0YjFmZWIyXkEyXkFqcGc@._V1_SX300.jpg'),
	(79, 'Dune', 'Sci-Fi', 'The son of a noble family is entrusted with the protection of the galaxy\'s most valuable asset.', 'Denis Villeneuve', 'Timothée Chalamet, Rebecca Ferguson, Zendaya', 2021, 155, 'English', 'https://m.media-amazon.com/images/M/MV5BMGJlMGM3NDAtOWNhMy00MWExLWI2MzEtMDQ0ZDIzZDY5ZmQ2XkEyXkFqcGc@._V1_SX300.jpg'),
	(80, 'The King\'s Speech', 'Biography', 'The story of King George VI\'s effort to overcome his stammer with the help of speech therapist Lionel Logue.', 'Tom Hooper', 'Colin Firth, Geoffrey Rush, Helena Bonham Carter', 2010, 118, 'English', 'https://m.media-amazon.com/images/M/MV5BMzU5MjEwMTg2Nl5BMl5BanBnXkFtZTcwNzM3MTYxNA@@._V1_SX300.jpg'),
	(81, 'Arrival', 'Sci-Fi', 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecrafts appear around the world.', 'Denis Villeneuve', 'Amy Adams, Jeremy Renner, Forest Whitaker', 2016, 116, 'English', 'https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_SX300.jpg'),
	(82, 'The Dark Knight Rises', 'Action', 'Eight years after the Joker\'s reign of anarchy, the Dark Knight faces a new foe: Bane.', 'Christopher Nolan', 'Christian Bale, Tom Hardy, Anne Hathaway', 2012, 164, 'English', 'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg'),
	(83, 'Frozen', 'Animation', 'When their kingdom becomes trapped in perpetual winter, fearless Anna joins forces with mountaineer Kristoff to find her sister, Elsa.', 'Chris Buck, Jennifer Lee', 'Kristen Bell, Idina Menzel, Jonathan Groff', 2013, 102, 'English', 'https://m.media-amazon.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_SX300.jpg'),
	(84, 'Zootopia', 'Animation', 'In a city of anthropomorphic animals, a bunny cop and a cynical con artist fox work together to uncover a conspiracy.', 'Byron Howard, Rich Moore, Jared Bush', 'Ginnifer Goodwin, Jason Bateman, Idris Elba', 2016, 108, 'English', 'https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_SX300.jpg'),
	(85, 'Ratatouille', 'Animation', 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.', 'Brad Bird, Jan Pinkava', 'Brad Garrett, Lou Romano, Patton Oswalt', 2007, 111, 'English', 'https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_SX300.jpg'),
	(86, 'The Lego Movie', 'Animation', 'An ordinary Lego construction worker discovers he is the prophesied "Special" tasked with saving the Lego world.', 'Phil Lord, Christopher Miller', 'Chris Pratt, Elizabeth Banks, Will Arnett', 2014, 100, 'English', 'https://m.media-amazon.com/images/M/MV5BMTg4MDk1ODExN15BMl5BanBnXkFtZTgwNzIyNjg3MDE@._V1_SX300.jpg'),
	(87, 'How to Train Your Dragon', 'Animation', 'A young Viking befriends a dragon, despite his tribe\'s beliefs about the creatures being dangerous.', 'Dean DeBlois, Chris Sanders', 'Jay Baruchel, Gerard Butler, Christopher Mintz-Plasse', 2010, 98, 'English', 'https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg'),
	(88, 'Minari', 'Drama', 'A Korean-American family moves to Arkansas in search of their own American Dream.', 'Lee Isaac Chung', 'Steven Yeun, Yeri Han, Alan S. Kim', 2020, 115, 'Korean', 'https://m.media-amazon.com/images/M/MV5BNWVmNDE3YzMtZWQ3Ny00YjhkLWEzN2QtZjNhYWNlMGI2N2NkXkEyXkFqcGc@._V1_SX300.jpg'),
	(89, 'The Banshees of Inisherin', 'Drama', 'Two lifelong friends find themselves at an impasse when one abruptly ends their relationship.', 'Martin McDonagh', 'Colin Farrell, Brendan Gleeson, Kerry Condon', 2022, 114, 'English', 'https://m.media-amazon.com/images/M/MV5BOTkzMWI4OTEtMTk0MS00MTUxLWI4NTYtYmRiNWM4Zjc1MGRhXkEyXkFqcGc@._V1_SX300.jpg'),
	(90, 'Everything Everywhere All At Once', 'Sci-Fi', 'An unlikely hero must channel her newfound powers to fight bizarre and bewildering dangers across multiverses.', 'Dan Kwan, Daniel Scheinert', 'Michelle Yeoh, Stephanie Hsu, Ke Huy Quan', 2022, 139, 'English', 'https://m.media-amazon.com/images/M/MV5BOWNmMzAzZmQtNDQ1NC00Nzk5LTkyMmUtNGI2N2NkOWM4MzEyXkEyXkFqcGc@._V1_SX300.jpg'),
	(91, 'Donnie Darko', 'Sci-Fi', 'A troubled teenager is plagued by visions of a man in a rabbit suit who manipulates him into committing a series of crimes.', 'Richard Kelly', 'Jake Gyllenhaal, Jena Malone, Mary McDonnell', 2001, 113, 'English', 'https://m.media-amazon.com/images/M/MV5BMWE3NTYzZmEtM2U5MS00MDZhLTk2ZTQtZTgzNjg0ZGQ5ZjM0XkEyXkFqcGc@._V1_SX300.jpg'),
	(92, 'No Country for Old Men', 'Crime', 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash.', 'Ethan Coen, Joel Coen', 'Tommy Lee Jones, Javier Bardem, Josh Brolin', 2007, 122, 'English', 'https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg'),
	(93, 'The Lighthouse', 'Drama', 'Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious island.', 'Robert Eggers', 'Robert Pattinson, Willem Dafoe, Valeriia Karaman', 2019, 109, 'English', 'https://m.media-amazon.com/images/M/MV5BMTI4MjFhMjAtNmQxYi00N2IxLWJjMGEtYWY1YmU3OTQ0Zjk3XkEyXkFqcGc@._V1_SX300.jpg'),
	(94, 'The Power of the Dog', 'Drama', 'Charismatic rancher Phil Burbank inspires fear and awe in those around him.', 'Jane Campion', 'Benedict Cumberbatch, Kirsten Dunst, Jesse Plemons', 2021, 126, 'English', 'https://m.media-amazon.com/images/M/MV5BNzgyMzA2NDEtZWUxNy00MDNmLTllMDYtNzZmNTU5ZWVmMzhlXkEyXkFqcGc@._V1_SX300.jpg'),
	(95, 'Knives Out', 'Mystery', 'A detective investigates the death of a patriarch of an eccentric, combative family.', 'Rian Johnson', 'Daniel Craig, Chris Evans, Ana de Armas', 2019, 130, 'English', 'https://m.media-amazon.com/images/M/MV5BZDU5ZTRkYmItZjg0Mi00ZTQwLThjMWItNWM3MTMxMzVjZmVjXkEyXkFqcGc@._V1_SX300.jpg'),
	(96, 'Paddington 2', 'Family', 'Paddington, now happily settled with the Brown family, takes up a series of odd jobs to buy a present for Aunt Lucy.', 'Paul King', 'Ben Whishaw, Hugh Grant, Hugh Bonneville', 2017, 103, 'English', 'https://m.media-amazon.com/images/M/MV5BNTk1YzlhMTUtZmU5MC00NmRmLTlkZjItYzQ0NTY4Y2NiNzc4XkEyXkFqcGc@._V1_SX300.jpg'),
	(97, 'The Farewell', 'Drama', 'A Chinese family discovers their grandmother has only a short while left to live and decide to keep her in the dark.', 'Lulu Wang', 'Awkwafina, Tzi Ma, Diana Lin', 2019, 100, 'Mandarin', 'https://m.media-amazon.com/images/M/MV5BYjdlZDI1OWYtZWU4MC00NDhkLThmOWEtMTZiODFhZThkMjA4XkEyXkFqcGc@._V1_SX300.jpg'),
	(98, 'Soul', 'Animation', 'A musician discovers his passion again after accidentally separating his soul from his body.', 'Pete Docter, Kemp Powers', 'Jamie Foxx, Tina Fey, Graham Norton', 2020, 100, 'English', 'https://m.media-amazon.com/images/M/MV5BZTZkYjA5MDEtMjY1ZC00ODk5LThjOTUtZDYxODEzYWNjMTU2XkEyXkFqcGc@._V1_SX300.jpg'),
	(99, 'Encanto', 'Animation', 'A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.', 'Jared Bush, Byron Howard, Charise Castro Smith', 'Stephanie Beatriz, María Cecilia Botero, John Leguizamo', 2021, 102, 'Spanish', 'https://m.media-amazon.com/images/M/MV5BOTY1YmU1ZTItMzNjZC00ZGU0LTk0MTEtZDgzN2QwOWVlNjZhXkEyXkFqcGc@._V1_SX300.jpg'),
	(100, 'Luca', 'Animation', 'On the Italian Riviera, an unlikely but strong friendship grows between a human and a sea monster disguised as a human.', 'Enrico Casarosa', 'Jacob Tremblay, Jack Dylan Grazer, Emma Berman', 2021, 95, 'English', 'https://m.media-amazon.com/images/M/MV5BMWMyNGNlZTktODVkNS00ZmMyLTk0NmUtNWVjOWU1MWMzZGMzXkEyXkFqcGc@._V1_SX300.jpg'),
	(101, 'The Batman', 'Action', 'Batman ventures into Gotham City\'s underworld when a sadistic killer leaves behind a trail of cryptic clues.', 'Matt Reeves', 'Robert Pattinson, Zoë Kravitz, Colin Farrell', 2022, 176, 'English', 'https://m.media-amazon.com/images/M/MV5BMmU5NGJlMzAtMGNmOC00YjJjLTgyMzUtNjAyYmE4Njg5YWMyXkEyXkFqcGc@._V1_SX300.jpg'),
	(102, 'Logan', 'Action', 'In a future where mutants are nearly extinct, Logan and an ailing Professor X protect a young mutant pursued by dark forces.', 'James Mangold', 'Hugh Jackman, Patrick Stewart, Dafne Keen', 2017, 137, 'English', 'https://m.media-amazon.com/images/M/MV5BM2JjODdkMGMtNmY2YS00OGM2LThiY2YtZGYyNzE4Nzc2ODA0XkEyXkFqcGc@._V1_SX300.jpg'),
	(103, 'Tenet', 'Sci-Fi', 'A secret agent manipulates the flow of time to prevent World War III.', 'Christopher Nolan', 'John David Washington, Robert Pattinson, Elizabeth Debicki', 2020, 150, 'English', 'https://m.media-amazon.com/images/M/MV5BMTU0ZjZlYTUtYzIwMC00ZmQzLWEwZTAtZWFhMWIwYjMxY2I3XkEyXkFqcGc@._V1_SX300.jpg'),
	(104, 'Doctor Strange', 'Sci-Fi', 'A neurosurgeon embarks on a journey of healing, only to be drawn into the world of the mystic arts.', 'Scott Derrickson', 'Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams', 2016, 115, 'English', 'https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg'),
	(105, 'Wonder Woman', 'Action', 'When a pilot crashes on her island, Diana learns about a great war raging in the outside world.', 'Patty Jenkins', 'Gal Gadot, Chris Pine, Robin Wright', 2017, 141, 'English', 'https://m.media-amazon.com/images/M/MV5BMjEzYmZkNjktODBmYi00NzNkLWIzMjItMjhkMWZiZTZlN2MwXkEyXkFqcGc@._V1_SX300.jpg'),
	(106, 'Cinderella', 'Romance', 'Ella\'s cruel stepmother prevents her from attending the Royal Ball, but help arrives from a magical source.', 'Kenneth Branagh', 'Lily James, Cate Blanchett, Richard Madden', 2015, 105, 'English', 'https://m.media-amazon.com/images/M/MV5BMjMxODYyODEzN15BMl5BanBnXkFtZTgwMDk4OTU0MzE@._V1_SX300.jpg'),
	(107, 'The Jungle Book', 'Adventure', 'After a threat from the tiger Shere Khan, Mowgli leaves his jungle home and embarks on a journey.', 'Jon Favreau', 'Neel Sethi, Bill Murray, Ben Kingsley', 2016, 106, 'English', 'https://m.media-amazon.com/images/M/MV5BMTc3NTUzNTI4MV5BMl5BanBnXkFtZTgwNjU0NjU5NzE@._V1_SX300.jpg'),
	(108, 'Moana', 'Animation', 'An adventurous teenager sails out on a daring mission to save her people, with the help of a demigod.', 'Ron Clements, John Musker', 'Auli\'i Cravalho, Dwayne Johnson, Rachel House', 2016, 107, 'English', 'https://m.media-amazon.com/images/M/MV5BMjI4MzU5NTExNF5BMl5BanBnXkFtZTgwNzY1MTEwMDI@._V1_SX300.jpg');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
